title: Aviorsys
description: Aviorsys Blog
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://aviorsys.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Randev Thaluksha"
image: /thumbnail-jumbo.png
twitter:
  username: #twitter username
#  site:
facebook:
  username: aviorsys
#  admins:
